### ISSUE TITLE
Missing the information in "About" field.

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AZ-801-Configuring-Windows-Server-Hybrid-Advanced-Services.ja-JP#26]
Missing the Link to "Github Pages"

**Comment by stonezy123** [comment]
not loclization issue

**Comment by stonezy123** [comment]
add it.

![image](https://user-images.githubusercontent.com/49666210/185027993-155460b8-8c51-455b-9dcb-3843a942c5f2.png)
