### ISSUE TITLE
Student + LAK Instructions documents have a Note with leading spaces, leading to undesired rendering.

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-801-Configuring-Windows-Server-Hybrid-Advanced-Services.ja-JP#27]
# <a name="module-00"></a>モジュール: 00
#### <a name="step-00"></a>ステップ:00

懸案事項の説明

再現手順:

This line, in the starting section of all student + LAK lab instructions appears to have ~16 additional/unneeded spaces:

'**メモ:** このラボをご自分のペースでクリックして進めることができる、 **[ラボの対話型シミュレーション](https://mslabs.cloudguides.com/guides/AZ-801%20Lab%20Simulation%20-%20Configuring%20security%20in%20Windows%20Server)** が用意されています。 対話型シミュレーションとホストされたラボの間に若干の違いがある場合がありますが、示されている主要な概念とアイデアは同じです。

This leads to undesirable display in both Github and ALH rendering:

![image](https://user-images.githubusercontent.com/49700217/228907579-8b930b62-27de-4069-85f1-657ab12dabc2.png)

If one removes the leading spaces, it displays as expected:

![image](https://user-images.githubusercontent.com/49700217/228907659-3ae226e4-fd31-4aa8-8c7c-7de3ed2dec49.png)

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
[Locfiles](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5UcnVlPC9TSFJQPjxTQVRPPlRydWU8L1NBVE8%2bPFNBTE8%2bRmFsc2U8L1NBTE8%2bPFFFPj4yPC9RRT48UVQ%2bPjxRUiBJZD0iMSIgQ1BJRD0iMCI%2bQ3VycmVudDtGaWxlcztIb3N0IENvbnRlbnQgU3RvcmU7RXF1YWw7V1dMPC9RUj48UVIgSWQ9IjIiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgQXNzZXQgSUQ7U3RhcnRzIFdpdGg7TEFCX0FLXzwvUVI%2bPFFSIElkPSIzIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtGaWxlcztIb3N0IENvbnRlbnQgR3JvdXA7RXF1YWw7V1dMLUxBQi1BWi04MDFfbWFzdGVyPC9RUj48UVIgSWQ9IjQiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0xvY0ZpbGVzO0xhbmd1YWdlO0VxdWFsO0phcGFuZXNlIChKYXBhbik8L1FSPjxRUiBJZD0iNiIgQ1BJRD0iMCI%2bYW5kO0N1cnJlbnQ7RmlsZXM7SG9zdCBGaWxlIFJlZmVyZW5jZTtDb250YWluczs1MDMzNTwvUVI%2bPC9RVD48Ukc%2bPEdDPk5VTEw8L0dDPjwvUkc%2bPC9WUFE%2b) to update
However the following are at PHO so blocked from updating at the moment
LAB_AK_02_Implementing_security_solutions_hybrid_scenarios.md
LAB_AK_07_Implementing_migration_in_hybrid_scenarios.md
LAB_AK_06_Upgrade_and_migrate_Windows Server.md
LAB_AK_05_Implementing_Azure-based_recovery_services.md
LAB_AK_09_Implementing_operational_monitoring_in_hybrid_scenarios.md

**Comment by chriscarty00** [comment]
Discussed with the PM and was instructed to update the older HB locfiles as this will seed the TM for the newer file.
