### ISSUE TITLE
 readme

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AZ-801-Configuring-Windows-Server-Hybrid-Advanced-Services.ja-JP#4]
Source:
It will be recommended that for every delivery, trainers check GitHub for any changes that may have been made to support the latest Azure services, and get the latest files for their delivery.

Current Translation:
すべての配信について、トレーナーは最新の Azure サービスをサポートするために行われた可能性がある変更をGitHub で確認し、配信用の最新のファイルを取得することをお勧めします。

Suggested Translation:
すべての配信について、トレーナーは GitHub を確認のうえ、最新の Azure サービスに対応するために変更された可能性のある情報を確認し、配信用の最新のファイルを取得することをお勧めします。

**Comment by Chenpeng21** [comment]
Fixed

**Comment by stonezy123** [comment]
![image](https://user-images.githubusercontent.com/49666210/160078747-20357f34-27db-46d0-a5b9-66edd21e9b0c.png)

fixed

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team
